package polyomino.dotfiles.theme

import polyomino.dotfiles.context.Context
import polyomino.dotfiles.error.{CommandError, PolyominoError}

object ThemeEngine:
  def run(ctx: Context, args: List[String]): Either[PolyominoError, Unit] =
    if args.isEmpty then
      polyomino.dotfiles.pickers.WofiPickers.runThemePicker(ctx, args)
    else
      val flavor = args.head
      var mode = "wallpaper"
      var customWallpaper: Option[String] = None
      var interval = "30m"

      var i = 1
      while i < args.length do
        args(i) match
          case "--flat" =>
            mode = "flat"
            i += 1
          case "--wallpaper" if i + 1 < args.length =>
            mode = "wallpaper"
            customWallpaper = Some(args(i + 1))
            i += 2
          case "--rotate" =>
            mode = "rotate"
            if i + 1 < args.length && !args(i + 1).startsWith("-") then
              interval = args(i + 1)
              i += 2
            else
              i += 1
          case _ =>
            i += 1

      applyTheme(ctx, flavor, mode, customWallpaper, interval)

  def getActivePalette(ctx: Context): Palette =
    val stateFile = ctx.configDir / "polyomino" / "theme" / "state"
    if os.exists(stateFile) then
      val flavorOpt = os.read.lines(stateFile).find(_.startsWith("FLAVOR=")).map(_.stripPrefix("FLAVOR="))
      flavorOpt.map(f => Palette.find(f, ctx)).getOrElse(Palette.FallbackPalette)
    else
      Palette.find("matriz", ctx)

  def applyTheme(
      ctx: Context,
      flavor: String,
      mode: String = "wallpaper",
      customWallpaper: Option[String] = None,
      interval: String = "30m"
  ): Either[PolyominoError, Unit] =
    println(s"\u001b[1;35m[polyomino theme]\u001b[0m Applying theme '$flavor' (mode: $mode)...")
    val palette = Palette.find(flavor, ctx)

    // Resolve wallpaper path
    val activeWallpaper = mode match
      case "flat" => ""
      case "rotate" => resolveWallpaperForFlavor(ctx, palette.name).getOrElse("")
      case _ => customWallpaper.getOrElse(resolveWallpaperForFlavor(ctx, palette.name).getOrElse(""))

    // 1. Write global state file ~/.config/polyomino/theme/state (read by Neovim and desktop apps)
    val stateDir = ctx.configDir / "polyomino" / "theme"
    os.makeDir.all(stateDir)
    val stateFile = stateDir / "state"
    val nvimColorscheme = s"${palette.name}-theme"
    val stateContent =
      s"""FLAVOR=${palette.name}
         |MODE=$mode
         |WALLPAPER=$activeWallpaper
         |WALLPAPER_SOURCE=${if mode == "rotate" then "rotate" else if mode == "flat" then "flat" else "single"}
         |INTERVAL=$interval
         |NVIM_COLORSCHEME=$nvimColorscheme
         |""".stripMargin
    os.write.over(stateFile, stateContent)
    println(s"  \u001b[32m[OK]\u001b[0m Global theme state written -> $stateFile")
    // 2a. Write token CSS file for external scripts (~/.config/polyomino/theme/tokens.css)
    val tokensFile = stateDir / "tokens.css"
    val tokensContent =
      s"""@define-color base ${palette.base};
@define-color mantle ${palette.mantle};
@define-color text ${palette.text};
@define-color accent ${palette.accent};
@define-color red ${palette.red};
@define-color green ${palette.green};
@define-color yellow ${palette.yellow};
@define-color blue ${palette.blue};"""
    os.write.over(tokensFile, tokensContent)
    println(s"  \u001b[32m[OK]\u001b[0m Token CSS written -> $tokensFile")

    // 2. Render Sway colors.conf (~/.config/sway/colors.conf)
    val swayDir = ctx.configDir / "sway"
    os.makeDir.all(swayDir)
    val swayColorsFile = swayDir / "colors.conf"
    val wallpaperDirective = if activeWallpaper.nonEmpty then
      s"output * bg \"$activeWallpaper\" fill"
    else
      "# No wallpaper"

    val swayColorsContent =
      s"""# Generated by polyomino dotfiles theme engine — flavor=${palette.name} mode=$mode
         |$wallpaperDirective
         |
         |# class                 border      bg          text        indicator   child_border
         |client.focused          ${palette.accent}   ${palette.base}   ${palette.text}   ${palette.accent}   ${palette.accent}
         |client.focused_inactive ${palette.mantle}   ${palette.base}   ${palette.text}   ${palette.mantle}   ${palette.mantle}
         |client.unfocused        ${palette.mantle}   ${palette.base}   #9ca3af             ${palette.mantle}   ${palette.mantle}
         |client.urgent           ${palette.red}      ${palette.base}   ${palette.red}      ${palette.red}      ${palette.red}
         |""".stripMargin
    os.write.over(swayColorsFile, swayColorsContent)
    println(s"  \u001b[32m[OK]\u001b[0m Rendered Sway colors -> $swayColorsFile")

    // 3. Render Kitty theme.conf & colors.conf (~/.config/kitty/)
    val kittyDir = ctx.configDir / "kitty"
    os.makeDir.all(kittyDir)
    val kittyThemeFile = kittyDir / "theme.conf"
    val kittyColorsFile = kittyDir / "colors.conf"
    val kittyContent =
      s"""# Generated by polyomino.dotfiles theme engine
         |background ${palette.base}
         |foreground ${palette.text}
         |selection_background ${palette.accent}
         |cursor ${palette.accent}
         |""".stripMargin
    os.write.over(kittyThemeFile, kittyContent)
    os.write.over(kittyColorsFile, kittyContent)
    println(s"  \u001b[32m[OK]\u001b[0m Rendered Kitty theme -> $kittyThemeFile")

    // 4. Render Waybar theme CSS & style.css (~/.config/waybar/)
    val waybarDir = ctx.configDir / "waybar"
    os.makeDir.all(waybarDir)
    val waybarThemeFile = waybarDir / "theme.css"
    val waybarStyleFile = waybarDir / "style.css"
    val waybarContent =
      s"""/* Generated by polyomino.dotfiles theme engine */
         |@define-color base ${palette.base};
         |@define-color mantle ${palette.mantle};
         |@define-color text ${palette.text};
         |@define-color accent ${palette.accent};
         |@define-color red ${palette.red};
         |@define-color green ${palette.green};
         |@define-color yellow ${palette.yellow};
         |@define-color blue ${palette.blue};
         |""".stripMargin
    os.write.over(waybarThemeFile, waybarContent)
    println(s"  \u001b[32m[OK]\u001b[0m Rendered Waybar theme -> $waybarThemeFile")

    val waybarStyleContent =
      s"""@import "${ctx.configDir / "polyomino" / "theme" / "tokens.css"}";
        |
        |* {
        |    font-family: "JetBrains Mono", "Symbols Nerd Font", Iosevka, archcraft, sans-serif;
        |    font-size: 13px;
        |    min-height: 0;
        |    border: none;
        |    border-radius: 0;
        |    transition: none;
        |}
        |
        |/* Enterprise CAD Waybar — three detached island segments over a transparent track */
        |window#waybar {
        |    background-color: transparent;
        |    color: @text;
        |    border: none;
        |    border-radius: 0px;
        |    margin: 6px 10px 0 10px;
        |}
        |
        |window#waybar.hidden {
        |   opacity: 0.5;
        |}
        |
        |/* Transparent track — the module lists carry no background of their own */
        |.modules-left,
        |.modules-center,
        |.modules-right {
        |    background: transparent;
        |    border: none;
        |    border-radius: 0px;
        |    padding: 0;
        |}
        |
        |/* Each group segment is its own floating island */
        |#left,
        |#center,
        |#right {
        |    background-color: @mantle;
        |    border: 1px solid #2A2E3D;
        |    border-radius: 0px;
        |    padding: 0 4px;
        |    margin: 3px 3px;
        |}
        |
        |/* CAD Dot Matrix separators */
        |#custom-matriz {
        |    color: #4A5568;
        |    font-size: 13px;
        |    padding: 0 6px;
        |}
        |
        |tooltip {
        |    background-color: @base;
        |    color: @text;
        |    border: 1px solid @accent;
        |    border-radius: 0px;
        |    padding: 8px 12px;
        |}
        |
        |tooltip label {
        |    color: @text;
        |    padding: 4px 8px;
        |    font-size: 13px;
        |}
        |
        |#workspaces {
        |    background-color: transparent;
        |    color: @accent;
        |    padding: 0;
        |}
        |
        |/* Clean workspace indicators — flat blocks without nested border outlines */
        |#workspaces button {
        |    min-width: 20px;
        |    padding: 2px 9px;
        |    margin: 3px 3px;
        |    background-color: transparent;
        |    color: @text;
        |    border: none;
        |    border-radius: 0px;
        |}
        |
        |#workspaces button label {
        |    padding: 0;
        |}
        |
        |#workspaces button.focused,
        |#workspaces button.active {
        |    background-color: @accent;
        |    color: @base;
        |    border: none;
        |    border-radius: 0px;
        |    font-weight: bold;
        |}
        |
        |#workspaces button:hover {
        |    background-color: @base;
        |    color: @accent;
        |    border: none;
        |}
        |
        |#workspaces button.urgent {
        |    background-color: @red;
        |    color: @base;
        |    border: none;
        |}
        |
        |/* Capsule contents inside the segments */
        |#clock,
        |#tray,
        |#window,
        |#network,
        |#bluetooth,
        |#pulseaudio,
        |#backlight,
        |#battery,
        |#cpu,
        |#memory,
        |#custom-notification,
        |#custom-spotify,
        |#mode {
        |    background-color: transparent;
        |    padding: 0 9px;
        |    color: @text;
        |    border: none;
        |    border-radius: 0px;
        |}
        |
        |#tray {
        |    padding: 0 8px;
        |}
        |
        |/* Collapse the window/mode capsules when nothing is focused so the
        |   clock stays centred in the middle pill instead of being shoved right.
        |   Waybar adds the `empty` class to sway/window when no window is focused. */
        |#window.empty,
        |#mode.empty {
        |    padding: 0;
        |    margin: 0;
        |    border: none;
        |}
        |
        |/* Center navigation clock capsule */
        |#clock {
        |    color: @text;
        |    font-weight: bold;
        |    padding: 0 11px;
        |    border: none;
        |}
        |
        |/* Right-side hardware capsule accents — Audio green, Wi-Fi teal, Battery gold */
        |#pulseaudio {
        |    color: @green;
        |}
        |
        |#network,
        |#network.wifi {
        |    color: #00D2D3;
        |}
        |
        |#bluetooth {
        |    color: #5DADE2;
        |}
        |
        |#battery {
        |    color: @accent;
        |}
        |
        |#cpu {
        |    color: #FF6B35;
        |}
        |
        |#memory {
        |    color: #9B59B6;
        |}
        |
        |#custom-spotify {
        |    color: @green;
        |}
        |
        |/* Trailing POLYOMINO pill */
        |#custom-polyomino {
        |    background-color: @accent;
        |    color: @base;
        |    font-weight: bold;
        |    padding: 0 12px;
        |    margin: 3px -4px 3px 6px;
        |    border-radius: 0px;
        |    border: none;
        |}
        |
        |#clock:hover,
        |#clock.active,
        |#tray:hover,
        |#network:hover,
        |#network.active,
        |#bluetooth:hover,
        |#bluetooth.active,
        |#pulseaudio:hover,
        |#pulseaudio.active,
        |#backlight:hover,
        |#backlight.active,
        |#battery:hover,
        |#battery.active,
        |#cpu:hover,
        |#cpu.active,
        |#memory:hover,
        |#memory.active,
        |#custom-notification:hover,
        |#custom-notification.active,
        |#custom-notification.open,
        |#custom-notification.open-window,
        |#custom-spotify:hover,
        |#mode:hover,
        |#mode.active {
        |    background-color: @base;
        |    border-radius: 0px;
        |}
        |
        |#battery.warning {
        |    color: @yellow;
        |}
        |
        |#battery.critical {
        |    color: @red;
        |}
        |
        |#network.disconnected {
        |    color: @red;
        |}
        |
        |#custom-notification.notification {
        |    color: @accent;
        |}
        |
        |#custom-notification.dnd-notification,
        |#custom-notification.dnd-none,
        |#custom-notification.dnd-inhibited-notification,
        |#custom-notification.dnd-inhibited-none {
        |    opacity: 0.6;
        |}
        |""".stripMargin
    os.write.over(waybarStyleFile, waybarStyleContent)
    println(s"  \u001b[32m[OK]\u001b[0m Rendered Waybar style -> $waybarStyleFile")

    // 5. Render Wofi & Rofi launcher themes (~/.config/wofi/, ~/.config/rofi/)
    val wofiDir = ctx.configDir / "wofi"
    os.makeDir.all(wofiDir)
    val wofiThemeFile = wofiDir / "theme.css"
    val wofiStyleFile = wofiDir / "style.css"
    val wofiContent =
      s"""/* Generated by polyomino.dotfiles theme engine — flavor=${palette.name} */
         |window {
         |    background-color: ${palette.mantle};
         |    color: ${palette.text};
         |    border: 2px solid ${palette.accent};
         |    border-radius: 0px;
         |    font-family: "JetBrainsMono Nerd Font";
         |    font-size: 13px;
         |}
         |#input {
         |    background-color: ${palette.base};
         |    color: ${palette.text};
         |    border: 1px solid ${palette.accent};
         |    border-radius: 0px;
         |    padding: 8px 12px;
         |    margin: 10px;
         |}
         |#inner-box {
         |    background-color: transparent;
         |    margin: 4px 6px;
         |}
         |#outer-box { padding: 2px; }
         |#scroll { margin: 2px; }
         |#entry {
         |    padding: 8px 12px;
         |    margin: 2px 6px;
         |    border-radius: 0px;
         |    background-color: ${palette.base};
         |    color: ${palette.text};
         |    border-left: 3px solid transparent;
         |}
         |#entry:selected {
         |    background-color: ${palette.accent};
         |    color: ${palette.base};
         |    border-radius: 0px;
         |    outline: none;
         |    border-left: 3px solid ${palette.text};
         |}
         |#entry:selected #text,
         |#text:selected {
         |    color: ${palette.base};
         |    font-weight: bold;
         |}
         |#text {
         |    color: ${palette.text};
         |}
         |#prompt {
         |    color: ${palette.accent};
         |    font-weight: bold;
         |}
         |""".stripMargin
    os.write.over(wofiThemeFile, wofiContent)
    os.write.over(wofiStyleFile, wofiContent)
    println(s"  \u001b[32m[OK]\u001b[0m Rendered Wofi theme -> $wofiStyleFile")

    val rofiDir = ctx.configDir / "rofi"
    os.makeDir.all(rofiDir)
    val rofiThemeFile = rofiDir / "theme.rasi"
    val rofiConfigFile = rofiDir / "config.rasi"
    val rofiThemeContent =
      s"""/* Generated by polyomino.dotfiles theme engine — flavor=${palette.name} */
         |* {
         |    bg: ${palette.mantle};
         |    fg: ${palette.text};
         |    accent: ${palette.accent};
         |    mantle: ${palette.base};
         |    border-col: ${palette.accent};
         |    font: "JetBrainsMono Nerd Font 12";
         |    background-color: transparent;
         |    text-color: @fg;
         |}
         |window {
         |    background-color: @bg;
         |    text-color: @fg;
         |    border: 2px;
         |    border-color: @border-col;
         |    border-radius: 0px;
         |    padding: 12px;
         |    width: 680px;
         |}
         |mainbox {
         |    children: [ inputbar, listview ];
         |}
         |inputbar {
         |    children: [ prompt, entry ];
         |    background-color: @mantle;
         |    border: 1px solid @border-col;
         |    border-radius: 0px;
         |    padding: 6px 10px;
         |    margin: 0 0 10px 0;
         |}
         |prompt {
         |    background-color: @accent;
         |    text-color: ${palette.base};
         |    padding: 4px 8px;
         |    border-radius: 0px;
         |    font-weight: bold;
         |}
         |entry {
         |    placeholder: "Search apps...";
         |    placeholder-color: #6c7086;
         |    padding: 4px 8px;
         |    text-color: @fg;
         |}
         |listview {
         |    lines: 6;
         |    columns: 2;
         |    fixed-height: false;
         |}
         |element {
         |    padding: 6px 10px;
         |    border-radius: 0px;
         |    background-color: @mantle;
         |    margin: 2px 4px;
         |    border: 1px solid transparent;
         |}
         |element selected {
         |    background-color: @accent;
         |    text-color: ${palette.base};
         |    border-radius: 0px;
         |    border: 1px solid @accent;
         |}
         |element-text {
         |    text-color: inherit;
         |}
         |element-icon {
         |    size: 24px;
         |    margin: 0 8px 0 0;
         |}
         |""".stripMargin
    val rofiConfigContent =
      s"""/* Generated by polyomino.dotfiles theme engine — flavor=${palette.name} */
        |configuration {
        |    modi: "drun,run,window";
        |    show-icons: true;
        |    icon-theme: "Papirus";
        |    terminal: "kitty";
        |    drun-display-format: "[⊞] {name}";
        |}
        |@theme "${rofiThemeFile.toString}"
        |""".stripMargin
    os.write.over(rofiThemeFile, rofiThemeContent)
    os.write.over(rofiConfigFile, rofiConfigContent)
    println(s"  \u001b[32m[OK]\u001b[0m Rendered Rofi theme -> $rofiThemeFile")

    // 6. Render Swaylock config (~/.config/swaylock/config)
    val swaylockDir = ctx.configDir / "swaylock"
    os.makeDir.all(swaylockDir)
    val swaylockConfigFile = swaylockDir / "config"
    val baseHex = palette.base.stripPrefix("#")
    val mantleHex = palette.mantle.stripPrefix("#")
    val textHex = palette.text.stripPrefix("#")
    val accentHex = palette.accent.stripPrefix("#")
    val redHex = palette.red.stripPrefix("#")

    val imageSetting = if activeWallpaper.nonEmpty then s"image=$activeWallpaper\nscaling=fill" else s"color=$baseHex"

    val swaylockContent =
      s"""# Generated by polyomino dotfiles theme engine
         |$imageSetting
         |font=JetBrainsMono Nerd Font
         |font-size=26
         |indicator-radius=115
         |indicator-thickness=14
         |ring-color=$mantleHex
         |inside-color=${baseHex}CC
         |text-color=$textHex
         |key-hl-color=$accentHex
         |bs-hl-color=$redHex
         |line-color=$mantleHex
         |inside-ver-color=${accentHex}CC
         |ring-ver-color=$accentHex
         |inside-wrong-color=${redHex}CC
         |ring-wrong-color=$redHex
         |inside-clear-color=${baseHex}CC
         |ring-clear-color=$accentHex
         |text-clear-color=$textHex
         |text-ver-color=$textHex
         |text-wrong-color=$textHex
         |show-failed-attempts
         |""".stripMargin
    os.write.over(swaylockConfigFile, swaylockContent)
    println(s"  \u001b[32m[OK]\u001b[0m Rendered Swaylock config -> $swaylockConfigFile")

    // 7. Update active-theme symlink for compatibility
    val activeThemeSymlink = swayDir / "active-theme"
    try
      if os.exists(activeThemeSymlink) || os.isLink(activeThemeSymlink) then os.remove(activeThemeSymlink)
      os.write.over(activeThemeSymlink, s"THEME_NAME=${palette.name}\nACCENT_COLOR=${palette.accent}\n")
    catch
      case _: Exception => ()

    // 8. Apply wallpaper live via Sway output bg
    if activeWallpaper.nonEmpty then
      try
        os.proc("timeout", "2", "swaymsg", "output", "*", "bg", activeWallpaper, "fill").call(check = false, stdout = os.Pipe, stderr = os.Pipe)
        println(s"  \u001b[32m[OK]\u001b[0m Applied wallpaper via Sway -> $activeWallpaper")
      catch
        case _: Exception => ()

    // 8b. Render Mako notification daemon config (~/.config/mako/config)
    val makoDir = ctx.configDir / "mako"
    os.makeDir.all(makoDir)
    val makoFile = makoDir / "config"
    val makoContent =
      s"""# Mako notification daemon configuration
         |# Generated by polyomino.dotfiles theme engine — flavor=${palette.name}
         |
         |output=*
         |width=360
         |margin=10
         |padding=12
         |border-size=2
         |border-radius=0
         |background-color=#161921
         |border-color=${palette.accent}
         |text-color=${palette.text}
         |font=JetBrainsMono Nerd Font 10
         |format=[ ⊞ ] %s\\n%b
         |default-timeout=5000
         |""".stripMargin
    os.write.over(makoFile, makoContent)
    println(s"  \u001b[32m[OK]\u001b[0m Rendered Mako config -> $makoFile")

    // 8c. Render SwayNC style stylesheet (~/.config/swaync/style.css)
    val swayncDir = ctx.configDir / "swaync"
    os.makeDir.all(swayncDir)
    val swayncFile = swayncDir / "style.css"
    val swayncContent =
      s"""/* Generated by polyomino.dotfiles theme engine — flavor=${palette.name} */
         |* {
         |    font-family: "JetBrainsMono Nerd Font", sans-serif;
         |    font-size: 13px;
         |}
         |
         |.control-center {
         |    background-color: ${palette.base};
         |    color: ${palette.text};
         |    border: 2px solid ${palette.accent};
         |    border-radius: 0px;
         |    padding: 14px;
         |}
         |
         |.control-center-list {
         |    background: transparent;
         |}
         |
         |.floating-notifications {
         |    background: transparent;
         |}
         |
         |.notification-row {
         |    outline: none;
         |    margin: 6px 0;
         |}
         |
         |.notification {
         |    background-color: ${palette.mantle};
         |    border: 1px solid ${palette.accent};
         |    border-radius: 0px;
         |    padding: 10px;
         |    color: ${palette.text};
         |}
         |
         |.notification-content {
         |    background: transparent;
         |    padding: 4px;
         |}
         |
         |.close-button {
         |    background: transparent;
         |    color: ${palette.text};
         |    border-radius: 0px;
         |    padding: 4px;
         |}
         |
         |.close-button:hover {
         |    background-color: ${palette.red};
         |    color: ${palette.base};
         |}
         |
         |.widget-title {
         |    color: ${palette.text};
         |    font-size: 15px;
         |    font-weight: bold;
         |    margin: 8px;
         |}
         |
         |.widget-title > button {
         |    background-color: ${palette.mantle};
         |    color: ${palette.text};
         |    border: 1px solid ${palette.accent};
         |    border-radius: 0px;
         |    padding: 4px 10px;
         |}
         |
         |.widget-title > button:hover {
         |    background-color: ${palette.accent};
         |    color: ${palette.base};
         |}
         |
         |.widget-dnd {
         |    background-color: ${palette.mantle};
         |    border: 1px solid ${palette.accent};
         |    border-radius: 0px;
         |    padding: 8px 12px;
         |    margin: 8px;
         |}
         |
         |.widget-dnd > switch {
         |    background-color: ${palette.base};
         |    border-radius: 0px;
         |    border: 1px solid ${palette.accent};
         |}
         |
         |.widget-dnd > switch:checked {
         |    background-color: ${palette.accent};
         |}
         |
         |.widget-mpris {
         |    background-color: ${palette.mantle};
         |    border: 1px solid ${palette.accent};
         |    border-radius: 0px;
         |    padding: 8px;
         |    margin: 8px;
         |}
         |
         |.widget-mpris-title {
         |    font-weight: bold;
         |    color: ${palette.text};
         |}
         |
         |.widget-mpris-subtitle {
         |    color: ${palette.text};
         |    opacity: 0.8;
         |}
         |
         |.widget-calendar {
         |    background-color: ${palette.mantle};
         |    border: 1px solid ${palette.accent};
         |    border-radius: 0px;
         |    padding: 12px;
         |    margin: 8px;
         |    font-size: 14px;
         |}
         |
         |.widget-calendar > calendar {
         |    background-color: transparent;
         |    color: ${palette.text};
         |    font-size: 14px;
         |    padding: 4px;
         |}
         |
         |.widget-calendar > calendar:selected {
         |    background-color: ${palette.accent};
         |    color: ${palette.base};
         |    border-radius: 0px;
         |}
         |
         |.widget-calendar > calendar.header {
         |    color: ${palette.accent};
         |    font-weight: bold;
         |    font-size: 15px;
         |    padding: 6px;
         |}
         |
         |.widget-calendar > calendar.button {
         |    color: ${palette.text};
         |    background: transparent;
         |    border-radius: 0px;
         |    padding: 4px 8px;
         |}
         |
         |.widget-calendar > calendar.button:hover {
         |    background-color: ${palette.accent};
         |    color: ${palette.base};
         |}
         |""".stripMargin
    os.write.over(swayncFile, swayncContent)
    println(s"  \u001b[32m[OK]\u001b[0m Rendered SwayNC style -> $swayncFile")

    // 9. Trigger live reloads across desktop applications
    polyomino.dotfiles.refresh.RefreshEngine.runRefresh(ctx)
    Right(())

  def resolveWallpaperForFlavor(ctx: Context, flavor: String): Option[String] =
    val wallpapersDir = ctx.dotfilesDir / "themes" / "wallpapers"
    if os.exists(wallpapersDir) then
      // Prefer any wallpaper that belongs to this flavor (`<flavor>.svg`,
      // `<flavor>_2.png`, `<flavor>-nebula.svg`, …); WallpaperEngine owns the
      // matching rules and is the source of truth for the picker/cycler too.
      polyomino.dotfiles.wallpaper.WallpaperEngine
        .wallpapersForFlavor(ctx, flavor)
        .headOption
        .map(_.toString)
        .orElse {
          os.list(wallpapersDir).find(f => f.ext == "svg" || f.ext == "png" || f.ext == "jpg").map(_.toString)
        }
    else None

  def listWallpapers(ctx: Context): Seq[String] =
    val wallpapersDir = ctx.dotfilesDir / "themes" / "wallpapers"
    if os.exists(wallpapersDir) then
      os.list(wallpapersDir)
        .filter(f => f.ext == "svg" || f.ext == "png" || f.ext == "jpg")
        .map(_.toString)
        .sorted
    else Nil
